
/*Data for the table `products` */


insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values ('S10_1678','1969 Harley Davidson Ultimate Chopper','Motorcycles','1:10','Min Lin Diecast','This replica features working kickstand, front suspension, gear-shift lever, footbrake lever, drive chain, wheels and steering. All parts are particularly delicate due to their precise scale and require special care and attention.',7933,48.81,95.70);
insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values ('S10_1949','1952 Alpine Renault 1300','Classic Cars','1:10','Classic Metal Creations','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',7305,98.58,214.30);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S10_2016','1996 Moto Guzzi 1100i','Motorcycles','1:10','Highway 66 Mini Classics','Official Moto Guzzi logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leather seats, luggage rack, dual exhaust pipes, small saddle bag located on handle bars, two-tone paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish.',6625,68.99,118.94);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S10_4698','2003 Harley-Davidson Eagle Drag Bike','Motorcycles','1:10','Red Start Diecast','Model features, official Harley Davidson logos and insignias, detachable rear wheelie bar, heavy diecast metal with resin parts, authentic multi-color tampo-printed graphics, separate engine drive belts, free-turning front fork, rotating tires and rear racing slick, certificate of authenticity, detailed engine, display stand\r\n, precision diecast replica, baked enamel finish, 1:10 scale model, removable fender, seat and tank cover piece for displaying the superior detail of the v-twin engine',5582,91.02,193.66);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S10_4757','1972 Alfa Romeo GTA','Classic Cars','1:10','Motor City Art Classics','Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',3252,85.68,136.00);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S10_4962','1962 LanciaA Delta 16V','Classic Cars','1:10','Second Gear Diecast','Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',6791,103.42,147.74);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_1099','1968 Ford Mustang','Classic Cars','1:12','Autoart Studio Design','Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color dark green.',68,95.34,194.57);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_1108','2001 Ferrari Enzo','Classic Cars','1:12','Second Gear Diecast','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',3619,95.59,207.80);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_1666','1958 Setra Bus','Trucks and Buses','1:12','Welly Diecast Productions','Model features 30 windows, skylights & glare resistant glass, working steering system, original logos',1579,77.90,136.67);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_2823','2002 Suzuki XREO','Motorcycles','1:12','Unimax Art Galleries','Official logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leather seats, luggage rack, dual exhaust pipes, small saddle bag located on handle bars, two-tone paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish.',9997,66.27,150.62);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_3148','1969 Corvair Monza','Classic Cars','1:18','Welly Diecast Productions','1:18 scale die-cast about 10\" long doors open, hood opens, trunk opens and wheels roll',6906,89.14,151.08);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_3380','1968 Dodge Charger','Classic Cars','1:12','Welly Diecast Productions','1:12 scale model of a 1968 Dodge Charger. Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color black',9123,75.16,117.44);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_3891','1969 Ford Falcon','Classic Cars','1:12','Second Gear Diecast','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',1049,83.05,173.02);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_3990','1970 Plymouth Hemi Cuda','Classic Cars','1:12','Studio M Art Models','Very detailed 1970 Plymouth Cuda model in 1:12 scale. The Cuda is generally accepted as one of the fastest original muscle cars from the 1970s. This model is a reproduction of one of the orginal 652 cars built in 1970. Red color.',5663,31.92,79.80);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_4473','1957 Chevy Pickup','Trucks and Buses','1:12','Exoto Designs','1:12 scale die-cast about 20\" long Hood opens, Rubber wheels',6125,55.70,118.50);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S12_4675','1969 Dodge Charger','Classic Cars','1:12','Welly Diecast Productions','Detailed model of the 1969 Dodge Charger. This model includes finely detailed interior and exterior features. Painted in red and white.',7323,58.73,115.16);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1097','1940 Ford Pickup Truck','Trucks and Buses','1:18','Studio M Art Models','This model features soft rubber tires, working steering, rubber mud guards, authentic Ford logos, detailed undercarriage, opening doors and hood,  removable split rear gate, full size spare mounted in bed, detailed interior with opening glove box',2613,58.33,116.67);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1129','1993 Mazda RX-7','Classic Cars','1:18','Highway 66 Mini Classics','This model features, opening hood, opening doors, detailed engine, rear spoiler, opening trunk, working steering, tinted windows, baked enamel finish. Color red.',3975,83.51,141.54);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1342','1937 Lincoln Berline','Vintage Cars','1:18','Motor City Art Classics','Features opening engine cover, doors, trunk, and fuel filler cap. Color black',8693,60.62,102.74);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1367','1936 Mercedes-Benz 500K Special Roadster','Vintage Cars','1:18','Studio M Art Models','This 1:18 scale replica is constructed of heavy die-cast metal and has all the features of the original: working doors and rumble seat, independent spring suspension, detailed interior, working steering system, and a bifold hood that reveals an engine so accurate that it even includes the wiring. All this is topped off with a baked enamel finish. Color white.',8635,24.26,53.91);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1589','1965 Aston Martin DB5','Classic Cars','1:18','Classic Metal Creations','Die-cast model of the silver 1965 Aston Martin DB5 in silver. This model includes full wire wheels and doors that open with fully detailed passenger compartment. In 1:18 scale, this model measures approximately 10 inches/20 cm long.',9042,65.96,124.44);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1662','1980s Black Hawk Helicopter','Planes','1:18','Red Start Diecast','1:18 scale replica of actual Army\'s UH-60L BLACK HAWK Helicopter. 100% hand-assembled. Features rotating rotor blades, propeller blades and rubber wheels.',5330,77.27,157.69);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1749','1917 Grand Touring Sedan','Vintage Cars','1:18','Welly Diecast Productions','This 1:18 scale replica of the 1917 Grand Touring car has all the features you would expect from museum quality reproductions: all four doors and bi-fold hood opening, detailed engine and instrument panel, chrome-look trim, and tufted upholstery, all topped off with a factory baked-enamel finish.',2724,86.70,170.00);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1889','1948 Porsche 356-A Roadster','Classic Cars','1:18','Gearbox Collectibles','This precision die-cast replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish.',8826,53.90,77.00);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_1984','1995 Honda Civic','Classic Cars','1:18','Min Lin Diecast','This model features, opening hood, opening doors, detailed engine, rear spoiler, opening trunk, working steering, tinted windows, baked enamel finish. Color yellow.',9772,93.89,142.25);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2238','1998 Chrysler Plymouth Prowler','Classic Cars','1:18','Gearbox Collectibles','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',4724,101.51,163.73);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2248','1911 Ford Town Car','Vintage Cars','1:18','Motor City Art Classics','Features opening hood, opening doors, opening trunk, wide white wall tires, front door arm rests, working steering system.',540,33.30,60.54);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2319','1964 Mercedes Tour Bus','Trucks and Buses','1:18','Unimax Art Galleries','Exact replica. 100+ parts. working steering system, original logos',8258,74.86,122.73);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2325','1932 Model A Ford J-Coupe','Vintage Cars','1:18','Autoart Studio Design','This model features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system, chrome-covered spare, opening doors, detailed and wired engine',9354,58.48,127.13);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2432','1926 Ford Fire Engine','Trucks and Buses','1:18','Carousel DieCast Legends','Gleaming red handsome appearance. Everything is here the fire hoses, ladder, axes, bells, lanterns, ready to fight any inferno.',2018,24.92,60.77);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2581','P-51-D Mustang','Planes','1:72','Gearbox Collectibles','Has retractable wheels and comes with a stand',992,49.00,84.48);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2625','1936 Harley Davidson El Knucklehead','Motorcycles','1:18','Welly Diecast Productions','Intricately detailed with chrome accents and trim, official die-struck logos and baked enamel finish.',4357,24.23,60.57);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2795','1928 Mercedes-Benz SSK','Vintage Cars','1:18','Gearbox Collectibles','This 1:18 replica features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system, chrome-covered spare, opening doors, detailed and wired engine. Color black.',548,72.56,168.75);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2870','1999 Indy 500 Monte Carlo SS','Classic Cars','1:18','Red Start Diecast','Features include opening and closing doors. Color: Red',8164,56.76,132.00);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2949','1913 Ford Model T Speedster','Vintage Cars','1:18','Carousel DieCast Legends','This 250 part reproduction includes moving handbrakes, clutch, throttle and foot pedals, squeezable horn, detailed wired engine, removable water, gas, and oil cans, pivoting monocle windshield, all topped with a baked enamel red finish. Each replica comes with an Owners Title and Certificate of Authenticity. Color red.',4189,60.78,101.31);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_2957','1934 Ford V8 Coupe','Vintage Cars','1:18','Min Lin Diecast','Chrome Trim, Chrome Grille, Opening Hood, Opening Doors, Opening Trunk, Detailed Engine, Working Steering System',5649,34.35,62.46);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_3029','1999 Yamaha Speed Boat','Ships','1:18','Min Lin Diecast','Exact replica. Wood and Metal. Many extras including rigging, long boats, pilot house, anchors, etc. Comes with three masts, all square-rigged.',4259,51.61,86.02);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_3136','18th Century Vintage Horse Carriage','Vintage Cars','1:18','Red Start Diecast','Hand crafted diecast-like metal horse carriage is re-created in about 1:18 scale of antique horse carriage. This antique style metal Stagecoach is all hand-assembled with many different parts.\r\n\r\nThis collectible metal horse carriage is painted in classic Red, and features turning steering wheel and is entirely hand-finished.',5992,60.74,104.72);

insert  into `products` (product_code, product_name, product_line, product_scale, product_vendor, product_description, quantity_in_stock, buy_price, MSRP) values('S18_3140','1903 Ford Model A','Vintage Cars','1:18','Unimax Art Galleries','Features opening trunk,  working steering system',3913,68.30,136.59);
